# Generated by Django 5.0.6 on 2024-07-18 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tareas",
            name="personas",
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=50)),
                ("finalizado", models.BooleanField(default=False)),
                ("personas", models.ManyToManyField(to="GESTOR_PROYECTOS.customuser")),
            ],
        ),
        migrations.CreateModel(
            name="Tarea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("no_iniciado", "No Iniciado"),
                            ("en_proceso", "En Proceso"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="no_iniciado",
                        max_length=50,
                    ),
                ),
                ("descripcion", models.TextField()),
                ("personas", models.ManyToManyField(to="GESTOR_PROYECTOS.customuser")),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tareas",
                        to="GESTOR_PROYECTOS.proyecto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Proyectos",
        ),
        migrations.DeleteModel(
            name="Tareas",
        ),
    ]
