# Generated by Django 5.0.6 on 2024-07-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0002_remove_tareas_personas_proyecto_tarea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="prioridad",
            field=models.CharField(
                choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")],
                default="Baja",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
