# Generated by Django 5.0.6 on 2024-07-23 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0003_tarea_prioridad"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="fecha",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
