# Generated by Django 5.0.6 on 2024-07-24 20:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0005_alter_tarea_personas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="personas",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
