# Generated by Django 5.0.6 on 2024-07-24 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0006_alter_proyecto_personas"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarea",
            name="fecha_final",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
