# Generated by Django 5.0.6 on 2024-07-25 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GESTOR_PROYECTOS", "0007_tarea_fecha_final"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
